package com.example.wallpapers.enums;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum AuthStatus {
    TOKEN_EXPIRED("TOKEN_EXPIRED"),
    TOKEN_UNSUPPORTED("TOKEN_UNSUPPORTED"),
    TOKEN_MALFORMED("TOKEN_MALFORMED"),
    TOKEN_INVALID_SIGNATURE("TOKEN_INVALID_SIGNATURE"),
    TOKEN_INVALID("TOKEN_INVALID"),
    TOKEN_VALID("TOKEN_VALID"),
    TOKEN_MISSING("TOKEN_MISSING"),
    SESSION_EXPIRED("SESSION_EXPIRED"),
    SESSION_CREATED("SESSION_CREATED"),
    SESSION_INVALID("SESSION_INVALID"),
    SESSION_DELETED("SESSION_DELETED"),
    CREDENTIAL_INVALID("CREDENTIAL_INVALID"),
    SERVER_ERROR("SERVER_ERROR");
    private final String value;
}
